### ISSUE TITLE
[pan] aliyun 

### ISSUE THREAD

**Issue by Alice52** [Alice52/archive#18]
1. docker compose
      
      ```yaml
      version: '3'
      services:
        sync:
          image: tickstep/aliyunpan-sync:v0.2.1
          container_name: aliyunpan-sync
          restart: always
          volumes:
            # 指定本地备份目录绝对路径：/tickstep/Documents/设计文档
            - /root/aliyunpan:/home/app/data:rw
            # （可选）可以指定JS插件sync_handler.js用于过滤文件，详见下面的插件说明
            #- ./plugin/js/sync_handler.js:/home/app/config/plugin/js/sync_handler.js
            # （推荐）挂载sync_drive同步数据库到本地，这样即使容器销毁，同步数据库还可以用于以后使用
            - /root/aliyunpan/sync_drive:/home/app/config/sync_drive
          environment:
            - TZ=Asia/Shanghai
            # refresh token
            - ALIYUNPAN_REFRESH_TOKEN=xxx
            # 上传下载链接类型：1-默认 2-阿里ECS环境
            - ALIYUNPAN_TRANSFER_URL_TYPE=1
            # 下载文件并发数
            - ALIYUNPAN_DOWNLOAD_PARALLEL=20
            # 上传文件并发数
            - ALIYUNPAN_UPLOAD_PARALLEL=20
            # 下载数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
            - ALIYUNPAN_DOWNLOAD_BLOCK_SIZE=1024
            # 上传数据块大小，单位为KB，默认为10240KB，建议范围1024KB~10240KB
            - ALIYUNPAN_UPLOAD_BLOCK_SIZE=10240
            # 指定网盘文件夹作为备份目录，不要指定根目录
            - ALIYUNPAN_PAN_DIR=/emoji
            # 备份模式：upload(备份本地文件到云盘), download(备份云盘文件到本地), sync(双向同步备份)
            - ALIYUNPAN_SYNC_MODE=sync
            # 优先级，只对双向同步备份模式有效。选项支持三种: time-时间优先，local-本地优先，pan-网盘优先
            - ALIYUNPAN_SYNC_PRIORITY=time
            # 是否显示文件备份过程日志，true-显示，false-不显示
            - ALIYUNPAN_SYNC_LOG=true
      
        webdav:
          image: tickstep/aliyunpan-webdav:v0.2.1
          container_name: aliyunpan-webdav
          restart: "no"
          ports:
            - 80:23077
          environment:
            - TZ=Asia/Shanghai
            # refresh token用于登录
            - ALIYUNPAN_REFRESH_TOKEN=xx
            # webdav 登录用户名
            - ALIYUNPAN_AUTH_USER=admin
            # webdav 登录密码
            - ALIYUNPAN_AUTH_PASSWORD=admin
            # 指定网盘文件夹作为webdav服务根目录
            - ALIYUNPAN_PAN_DIR=/
            # 上传下载链接类型：1-默认 2-阿里ECS环境(ECS必须是经典网络类型)
            - ALIYUNPAN_TRANSFER_URL_TYPE=2
            # 上传数据块大小，单位为KB，默认为1024KB，建议范围1024KB~10240KB
            - ALIYUNPAN_BLOCK_SIZE=10240
      ````
